name: dlai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - langchain
  - openai
  - notebook
  - python-dotenv
  - pandas
  - pypdf
  - tiktoken
  - chromadb
  - lark
  - docarray
  - wikipedia
  - numexpr
  - scikit-learn
  - panel